In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score  
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("empscore.csv")
data

experience   test score  interview score  salary
0          NaN         8.0                9   50000
1          NaN         8.0                6   45000
2          5.0         6.0                7   60000
3          2.0        10.0               10   65000
4          7.0         9.0                6   70000
5          3.0         7.0               10   62000
6         10.0         NaN                7   72000
7         11.0         7.0                8   80000

In [3]:
x=data.iloc[:,0:3].values
x

array([[nan,  8.,  9.],
       [nan,  8.,  6.],
       [ 5.,  6.,  7.],
       [ 2., 10., 10.],
       [ 7.,  9.,  6.],
       [ 3.,  7., 10.],
       [10., nan,  7.],
       [11.,  7.,  8.]])

In [4]:
y=data[['salary']].values
y

array([[50000],
       [45000],
       [60000],
       [65000],
       [70000],
       [62000],
       [72000],
       [80000]], dtype=int64)

## Remove missing value for x

In [5]:

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:,:2])
x[:,:2] = imputer.transform(x[:,:2])
x

array([[ 6.33333333,  8.        ,  9.        ],
       [ 6.33333333,  8.        ,  6.        ],
       [ 5.        ,  6.        ,  7.        ],
       [ 2.        , 10.        , 10.        ],
       [ 7.        ,  9.        ,  6.        ],
       [ 3.        ,  7.        , 10.        ],
       [10.        ,  7.85714286,  7.        ],
       [11.        ,  7.        ,  8.        ]])

# Split data into x and y and then predict

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state=0)

mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [7]:
x_train

array([[11.        ,  7.        ,  8.        ],
       [ 2.        , 10.        , 10.        ],
       [ 6.33333333,  8.        ,  9.        ],
       [ 3.        ,  7.        , 10.        ],
       [ 7.        ,  9.        ,  6.        ]])

In [8]:
x_test

array([[10.        ,  7.85714286,  7.        ],
       [ 5.        ,  6.        ,  7.        ],
       [ 6.33333333,  8.        ,  6.        ]])

In [9]:
y_train

array([[80000],
       [65000],
       [50000],
       [62000],
       [70000]], dtype=int64)

In [10]:
y_test

array([[72000],
       [60000],
       [45000]], dtype=int64)

In [11]:
y_predict = mlr.predict(x_test)
y_predict

array([[72814.6524349 ],
       [62527.74989244],
       [67381.1128639 ]])

In [12]:
print(mlr.score(x_test, y_test))

-0.387889046817558
